server.port=9090

# ??????? (????????????)
spring.datasource.url=jdbc:mysql://localhost:3307/media_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ????
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB

# ????
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ==============================
# AI ???? (?????)
# ==============================
ai.deepseek.api-key=sk-iwvgacxqaiezdiqsekdowcmjhwsftbperckcjtkmzlghnukc
ai.deepseek.base-url=https://api.siliconflow.cn/v1
ai.aliyun.api-key=sk-f6e51d42ad69494bb3c445895356b3ce


# ==========================================
# Redis ?? (????)
# ==========================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=3000ms


# ==========================================
# MinIO ?? (????)
# ==========================================
minio.endpoint=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=media



# ==========================================
# ????????
# ==========================================
# yt-dlp ????? (??????????????)
tool.ytdlp.path=D:/yt-dlp/yt-dlp.exe

tool.ffmpeg.dir=D:/ffmpeg/bin


# ================= RocketMQ ?? =================
# ?????? Docker ???????
rocketmq.name-server=127.0.0.1:9876
# ??????????????
rocketmq.producer.group=video-analysis-group
# ?????? (??)
rocketmq.producer.send-message-timeout=3000